[package]
name = "sqlx_structs"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.44.2", features = ["rt-multi-thread"] }